[versions]
# Plugin Versions
kotlin = "1.9.21"
androidGrdlePlugin = "8.2.0"

[libraries]


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGrdlePlugin" }
