[versions]
# Plugin Versions
kotlin = "1.9.21"
androidGrdlePlugin = "8.2.0"

# Library Versions
annotation = "1.7.1"


[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGrdlePlugin" }
